name: Thin Ice
favicon: null
layout_spectrum: 0.56682
typography_spectrum: 0.49533
title: thin ice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fed000'
    - '#fef05b'
    - '#eda600'
    - '#1e1f11'
    - '#9a6300'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
