name: Thin Ice
favicon: null
layout_spectrum: 0.56682
typography_spectrum: 0.58242
title: 50 drops of sweetness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002d37'
    - '#a2af77'
    - '#71966a'
    - '#d6c07c'
    - '#005451'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
